_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 5
                - 14
                - 23
                - 55
                - 62
            "4": 3.12.2
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 256
ckpt_path:
    value: checkpoint.pt
dropout_p:
    value: 0.1
epochs:
    value: 15
hidden_layer_width:
    value: 64
lr:
    value: 0.0001
optim_type:
    value: Adam
project_name:
    value: wandb_demo
